
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitor.wangjl.dev.wangjl.dev
  resources:
  - turbines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.wangjl.dev.wangjl.dev
  resources:
  - turbines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitor.wangjl.dev.wangjl.dev
  resources:
  - turbineservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.wangjl.dev.wangjl.dev
  resources:
  - turbineservers/status
  verbs:
  - get
  - patch
  - update
