# permissions for end users to view turbines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: turbine-viewer-role
rules:
- apiGroups:
  - monitor.wangjl.dev.wangjl.dev
  resources:
  - turbines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.wangjl.dev.wangjl.dev
  resources:
  - turbines/status
  verbs:
  - get
