# permissions for end users to edit turbines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: turbine-editor-role
rules:
- apiGroups:
  - monitor.wangjl.dev.wangjl.dev
  resources:
  - turbines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.wangjl.dev.wangjl.dev
  resources:
  - turbines/status
  verbs:
  - get
